### PR TITLE
Adding CODE memory type and changing the API to: CODE,RW_DATA,DEVICE

### PR DESCRIPTION
**Pull request by TalHal**
Hi Ash,
Following your reply to me in the support case. I decided to pull request :).
The change include the following:
1. Adding CODE memory type - which is based on Normal memory type but it is Read-only executable,
2. Changing the API because now we have 3 types: CODE(based on Normal),RW_DATA(based on Normal), DEVICE (unchanged).

### CODE REVIEW

**Review by ashwio — CHANGES_REQUESTED** [review]
Hi Tal,

Many thanks for submitting this pull request! This is a very comprehensive update and much appreciated!

My only nitpick is the addition to pgtt/mmu.py on line 107, setting SCTLR_ELx.A=1. Typically we do want to allow unaligned accesses to Normal memory for performance reasons, perhaps this would be better served as a flag? I recommend deleting this line and I've created [this issue](https://github.com/ashwio/arm64-pgtable-tool/issues/2) to track adding this as a flag.

Also, we should add a CONTRIBUTORS file to the top-level repo with your name in it. Do you want to add that as part of the pull request, or shall I create it as a commit on top of yours?

Thanks,
Ash.

**Comment by TalHal** [comment]
Ash,
Thank you for the review.
I have removed line 107.
Adding it as a flag is a good idea.
I added it in the first place because working without alignment check with DEVICE memory is pretty risky. If I am not mistaken "Arm trusted FW" enable it by default.
Regarding the CONTRIBUTORS you can add it on top of my commits.

Thanks,
Tal.

**Comment by ashwio** [comment]
Hey Tal,

Many thanks for making the changes, I'll merge this in now. RE Alignment checking, note that unaligned accesses to Device type memory will always give an Alignment Fault, the `SCTLR_ELx.A` bit only applies to accesses to Normal type memory and causes the same Alignment Fault that you always get for Device memory.

You're right though that some projects set it by default, so I'll look to get the flag added soon :) 

Thanks,
Ash.

**Comment by ashwio** [comment]
Hi Tal, reverting and remerging this as a rebase rather than a squash so that it doesn't lose your author info (sorry, new to the way GitHub does things!)

**Comment by ashwio** [comment]
Think that should look right now! Thanks again

**Pull request merged**
